### monitor get all tasks
GET http://{{host}}:10000/task/get
Accept: application/json

### monitor open sys
GET http://{{host}}:10000/task/open_system?flag=true
Accept: application/json

### monitor test task
GET http://{{host}}:10000/task/test?name={{name}}
Accept: application/json

### monitor add task
GET http://{{host}}:10000/task/add?name={{name}}
Accept: application/json

### monitor del task
GET http://{{host}}:10000/task/del?id=d2b066d3-47b2-a714-624d-aa3316165d64
Accept: application/json

### monitor start task
GET http://{{host}}:10000/task/start?id=da44db68-8858-fe65-10ec-216f59f22edd
Accept: application/json

### monitor stop task
GET http://{{host}}:10000/task/stop?id=a32fcdea-ebb8-a342-cfb1-41dae9219060
Accept: application/json

### monitor get res
GET http://{{host}}:10000/res/get
Accept: application/json
